//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string NIC { get; set; }
        public Nullable<int> Course_id { get; set; }
        public Nullable<int> Batch_id { get; set; }
        public Nullable<int> Tel_No { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Course Course { get; set; }
    }
}
